version: 2
updates:
  - package-ecosystem: maven
    target-branch: "develop"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "org.jreleaser:jdks-maven-plugin"
        versions: ["1.24.0"]
  - package-ecosystem: "github-actions"
    target-branch: "develop"
    directory: "/"
    schedule:
      interval: "daily"
