/*
 * Copyright 2013 National Bank of Belgium
 *
 * Licensed under the EUPL, Version 1.1 or – as soon they will be approved 
 * by the European Commission - subsequent versions of the EUPL (the "Licence");
 * You may not use this work except in compliance with the Licence.
 * You may obtain a copy of the Licence at:
 * 
 * http://ec.europa.eu/idabc/eupl
 * 
 * Unless required by applicable law or agreed to in writing, software 
 * distributed under the Licence is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the Licence for the specific language governing permissions and 
 * limitations under the Licence.
 */
package demetra.desktop.anomalydetection.report;

import java.awt.event.ItemEvent;
import java.util.List;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author maggima
 */
public class CheckLastSortPanel extends javax.swing.JPanel {

    /**
     * Creates new form CheckLastSortPanel
     */
    public CheckLastSortPanel() {
        initComponents();
        fillList();
    }
    
    private void fillList() {
        List<CheckLastReportFactory> factories = CheckLastReportManager.getDefault().getFactories();        
        DefaultComboBoxModel<CheckLastReportFactory> model = new DefaultComboBoxModel(factories.toArray());
        reportCombo.setModel(model);
    }
    
    public CheckLastReportFactory getFactory() {
        return (CheckLastReportFactory)reportCombo.getSelectedItem();
    }

    public AnomalyPojoComparator getComparator() {
        if (ascendingRadio.isSelected()) {
            switch (sortComboBox.getSelectedIndex()) {
                case 1:
                    return AnomalyPojoComparator.Relative_Asc;
                case 2:
                    return AnomalyPojoComparator.Absolute_Asc;
                case 3:
                    return AnomalyPojoComparator.Period_Asc;
                default:
                    return null;
            }
        } else {
            switch (sortComboBox.getSelectedIndex()) {
                case 1:
                    return AnomalyPojoComparator.Relative_Desc;
                case 2:
                    return AnomalyPojoComparator.Absolute_Desc;
                case 3:
                    return AnomalyPojoComparator.Period_Desc;
                default:
                    return null;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        orderButtonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        sortComboBox = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        ascendingRadio = new javax.swing.JRadioButton();
        descendingRadio = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        reportCombo = new javax.swing.JComboBox();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(CheckLastSortPanel.class, "CheckLastSortPanel.jPanel1.border.title"))); // NOI18N
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));

        sortComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None", "Relative Error", "Absolute Error", "Period" }));
        sortComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                sortComboBoxItemStateChanged(evt);
            }
        });
        jPanel1.add(sortComboBox);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.X_AXIS));

        orderButtonGroup.add(ascendingRadio);
        org.openide.awt.Mnemonics.setLocalizedText(ascendingRadio, org.openide.util.NbBundle.getMessage(CheckLastSortPanel.class, "CheckLastSortPanel.ascendingRadio.text")); // NOI18N
        ascendingRadio.setEnabled(false);
        jPanel3.add(ascendingRadio);

        orderButtonGroup.add(descendingRadio);
        descendingRadio.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(descendingRadio, org.openide.util.NbBundle.getMessage(CheckLastSortPanel.class, "CheckLastSortPanel.descendingRadio.text")); // NOI18N
        descendingRadio.setEnabled(false);
        jPanel3.add(descendingRadio);

        jPanel1.add(jPanel3);

        add(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(CheckLastSortPanel.class, "CheckLastSortPanel.jPanel2.border.title"))); // NOI18N
        jPanel2.setLayout(new java.awt.BorderLayout());

        reportCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(reportCombo, java.awt.BorderLayout.CENTER);

        add(jPanel2);
    }// </editor-fold>//GEN-END:initComponents

    private void sortComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_sortComboBoxItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            ascendingRadio.setEnabled(sortComboBox.getSelectedIndex() != 0);
            descendingRadio.setEnabled(sortComboBox.getSelectedIndex() != 0);
        }
    }//GEN-LAST:event_sortComboBoxItemStateChanged
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ascendingRadio;
    private javax.swing.JRadioButton descendingRadio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.ButtonGroup orderButtonGroup;
    private javax.swing.JComboBox reportCombo;
    private javax.swing.JComboBox sortComboBox;
    // End of variables declaration//GEN-END:variables
}
