/*
 * Copyright 2016 National Bank of Belgium
 *
 * Licensed under the EUPL, Version 1.1 or – as soon they will be approved 
 * by the European Commission - subsequent versions of the EUPL (the "Licence");
 * You may not use this work except in compliance with the Licence.
 * You may obtain a copy of the Licence at:
 * 
 * http://ec.europa.eu/idabc/eupl
 * 
 * Unless required by applicable law or agreed to in writing, software 
 * distributed under the Licence is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the Licence for the specific language governing permissions and 
 * limitations under the Licence.
 */
package ec.nbdemetra.sa;

import ec.tss.sa.SaItem;
import ec.tss.tsproviders.utils.MultiLineNameUtil;

/**
 * Panel used in the delete confirmation dialog of Multi SA Processing.
 * @author Mats Maggi
 */
public class DeleteActionPanel extends javax.swing.JPanel {

    private SaItem[] items;

    public DeleteActionPanel() {
        initComponents();
    }
    
    public DeleteActionPanel(SaItem[] items) {
        this();
        this.items = items;
        refreshItems();
    }

    private void refreshItems() {
        String[] names = new String[items.length];
        for (int i = 0; i < items.length; i++) {
            names[i] = MultiLineNameUtil.join(items[i].getTs().getName());
        }
        itemList.setListData(names);
        itemList.setSelectionInterval(0, items.length-1);
    }

    public void setItems(SaItem[] items) {
        this.items = items;
        refreshItems();
    }
    
    public int[] getSelectedIndices() {
        return itemList.getSelectedIndices();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deleteMessageLabel = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        itemList = new javax.swing.JList<>();

        setPreferredSize(new java.awt.Dimension(340, 150));
        setLayout(new java.awt.BorderLayout());

        org.openide.awt.Mnemonics.setLocalizedText(deleteMessageLabel, "Are you sure you want to delete the following items ?"); // NOI18N
        deleteMessageLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 5, 5));
        add(deleteMessageLabel, java.awt.BorderLayout.NORTH);

        itemList.setModel(new javax.swing.AbstractListModel<String>() {
            final String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrollPane.setViewportView(itemList);

        add(scrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel deleteMessageLabel;
    private javax.swing.JList<String> itemList;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables

}

