/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package demetra.desktop.highfreq.ui;

import jdplus.highfreq.extendedairline.decomposiiton.ExtendedAirlineDecompositionDocument;
import demetra.desktop.highfreq.ExtendedAirlineDecompositionDocumentManager;
import demetra.desktop.workspace.DocumentUIServices;
import demetra.desktop.ui.processing.TsProcessingViewer;
import demetra.desktop.workspace.WorkspaceFactory;
import demetra.desktop.workspace.WorkspaceItem;
import demetra.desktop.workspace.ui.WorkspaceTsTopComponent;
import org.openide.windows.TopComponent;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.explorer.ExplorerManager;
import org.openide.explorer.ExplorerUtils;
import org.openide.util.NbBundle;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(dtd = "-//demetra.desktop.highfreq//ExtendedAirlineDecomposition//EN",
        autostore = false)
@TopComponent.Description(preferredID = "ExtendedAirlineDecompositionTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_NEVER)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@ActionID(category = "Seasonal Adjustment", id = "demetra.desktop.highfreq.ExtendedAirlineDecompositionTopComponent")
@ActionReference(path = "Menu/Statistical methods/Seasonal Adjustment/Single Analysis", position = 20000, separatorBefore=19000)
@TopComponent.OpenActionRegistration(displayName = "#CTL_ExtendedAirlineDecompositionAction")
@NbBundle.Messages({
    "CTL_ExtendedAirlineDecompositionAction=Extended airline decomposition",
    "CTL_ExtendedAirlineDecompositionTopComponent=Extended Airline Decomposition Window",
    "HINT_ExtendedAirlineDecompositionTopComponent=This is a Extended Airline Decomposition window"
})
public final class ExtendedAirlineDecompositionTopComponent extends WorkspaceTsTopComponent<ExtendedAirlineDecompositionDocument> {

    private final ExplorerManager mgr = new ExplorerManager();

    private static ExtendedAirlineDecompositionDocumentManager manager() {
        return WorkspaceFactory.getInstance().getManager(ExtendedAirlineDecompositionDocumentManager.class);
    }

    public ExtendedAirlineDecompositionTopComponent() {
        this(null);
    }

    public ExtendedAirlineDecompositionTopComponent(WorkspaceItem<ExtendedAirlineDecompositionDocument> doc) {
        super(doc);
        initComponents();
        setToolTipText(NbBundle.getMessage(ExtendedAirlineDecompositionTopComponent.class, "HINT_ExtendedAirlineDecompositionTopComponent"));
        associateLookup(ExplorerUtils.createLookup(mgr, getActionMap()));
    }

    @Override
    public ExplorerManager getExplorerManager() {
        return mgr;
    }

    @Override
    protected TsProcessingViewer initViewer() {
        return TsProcessingViewer.create(getElement(), DocumentUIServices.forDocument(ExtendedAirlineDecompositionDocument.class));
   }

    @Override
    public WorkspaceItem<ExtendedAirlineDecompositionDocument> newDocument() {
        return manager().create(WorkspaceFactory.getInstance().getActiveWorkspace());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    @Override
    protected String getContextPath() {
        return ExtendedAirlineDecompositionDocumentManager.CONTEXTPATH;
    }
}
