/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/NetBeansModuleDevelopment-files/template_mypluginPanel.java to edit this template
 */
package demetra.desktop.ui;

import demetra.desktop.ColorSchemeManager;
import demetra.desktop.DemetraUI;
import demetra.desktop.NamedService;
import demetra.desktop.TsActions;
import demetra.desktop.components.JObsFormatComponent;
import demetra.desktop.components.JTsChart;
import demetra.desktop.components.parts.HasColorSchemeSupport;
import demetra.desktop.components.parts.HasTsCollection;
import ec.util.chart.ColorScheme;
import java.awt.Image;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.beans.PropertyVetoException;
import java.beans.VetoableChangeListener;
import java.util.stream.Collectors;
import org.openide.explorer.ExplorerManager;
import org.openide.nodes.Node;
import org.openide.util.ImageUtilities;

final class CommonUIPanel extends javax.swing.JPanel implements VetoableChangeListener, PropertyChangeListener {

    private final CommonUIOptionsPanelController controller;
    final JTsChart colorSchemePreviewer;

    CommonUIPanel(CommonUIOptionsPanelController controller) {
        this.controller = controller;
        initComponents();
        colorSchemePreviewer = new JTsChart();
        colorSchemePreviewer.setTsCollection(DemoTsBuilder.randomTsCollection(3));
        colorSchemePreviewer.setTsAction(TsActions.NO_ACTION);
        colorSchemePreviewer.setTsUpdateMode(HasTsCollection.TsUpdateMode.None);
        chartPreviewPanel.add(colorSchemePreviewer);

        jSlider1.setMinimum(10);
        jSlider1.setMaximum(200);
        jSlider1.setValue(100);
        jSlider1.setMajorTickSpacing(100);
        jSlider1.setMinorTickSpacing(5);
        jSlider1.setPaintTicks(true);
        jSlider1.setPaintLabels(true);
        jSlider1.setSnapToTicks(true);
        jSlider1.setLabelTable(jSlider1.createStandardLabels(100, 100));
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chartsPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        colorSchemeChoicePanel = new demetra.desktop.nodes.NamedServiceChoicePanel();
        colorSchemeLabel = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 0), new java.awt.Dimension(40, 32767));
        chartPreviewPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        dataFormatLabel = new javax.swing.JLabel();
        dataFormatComponent = new demetra.desktop.components.JObsFormatComponent();
        variousPanel = new javax.swing.JPanel();
        growthChartsPanel = new javax.swing.JPanel();
        growthLastYears = new javax.swing.JSpinner();
        lastYearsLabel = new javax.swing.JLabel();
        htmlFontPanel = new javax.swing.JPanel();
        jSlider1 = new javax.swing.JSlider();
        popupMenuPanel = new javax.swing.JPanel();
        iconsVisibleCB = new javax.swing.JCheckBox();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        chartsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(CommonUIPanel.class, "CommonUIPanel.chartsPanel.border.title"))); // NOI18N
        chartsPanel.setLayout(new java.awt.BorderLayout(0, 15));

        jPanel2.setLayout(new java.awt.BorderLayout(10, 0));

        colorSchemeChoicePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.add(colorSchemeChoicePanel, java.awt.BorderLayout.CENTER);

        org.openide.awt.Mnemonics.setLocalizedText(colorSchemeLabel, org.openide.util.NbBundle.getMessage(CommonUIPanel.class, "CommonUIPanel.colorSchemeLabel.text")); // NOI18N
        jPanel2.add(colorSchemeLabel, java.awt.BorderLayout.WEST);
        jPanel2.add(filler2, java.awt.BorderLayout.LINE_END);

        chartsPanel.add(jPanel2, java.awt.BorderLayout.NORTH);

        chartPreviewPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        chartPreviewPanel.setMaximumSize(new java.awt.Dimension(100, 150));
        chartPreviewPanel.setMinimumSize(new java.awt.Dimension(100, 150));
        chartPreviewPanel.setPreferredSize(new java.awt.Dimension(100, 150));
        chartPreviewPanel.setLayout(new java.awt.BorderLayout());
        chartsPanel.add(chartPreviewPanel, java.awt.BorderLayout.CENTER);

        jPanel3.setLayout(new java.awt.BorderLayout(10, 0));

        org.openide.awt.Mnemonics.setLocalizedText(dataFormatLabel, org.openide.util.NbBundle.getMessage(CommonUIPanel.class, "CommonUIPanel.dataFormatLabel.text")); // NOI18N
        jPanel3.add(dataFormatLabel, java.awt.BorderLayout.WEST);
        jPanel3.add(dataFormatComponent, java.awt.BorderLayout.CENTER);

        chartsPanel.add(jPanel3, java.awt.BorderLayout.SOUTH);

        add(chartsPanel);

        variousPanel.setLayout(new javax.swing.BoxLayout(variousPanel, javax.swing.BoxLayout.PAGE_AXIS));

        growthChartsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(CommonUIPanel.class, "CommonUIPanel.growthChartsPanel.border.title"))); // NOI18N

        growthLastYears.setModel(new javax.swing.SpinnerNumberModel(4, 1, 15, 1));

        org.openide.awt.Mnemonics.setLocalizedText(lastYearsLabel, org.openide.util.NbBundle.getMessage(CommonUIPanel.class, "CommonUIPanel.lastYearsLabel.text")); // NOI18N

        javax.swing.GroupLayout growthChartsPanelLayout = new javax.swing.GroupLayout(growthChartsPanel);
        growthChartsPanel.setLayout(growthChartsPanelLayout);
        growthChartsPanelLayout.setHorizontalGroup(
            growthChartsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(growthChartsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lastYearsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(growthLastYears, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        growthChartsPanelLayout.setVerticalGroup(
            growthChartsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(growthChartsPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(growthChartsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastYearsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(growthLastYears, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        variousPanel.add(growthChartsPanel);

        htmlFontPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(CommonUIPanel.class, "CommonUIPanel.htmlFontPanel.border.title"))); // NOI18N
        htmlFontPanel.setLayout(new java.awt.GridLayout());
        htmlFontPanel.add(jSlider1);

        variousPanel.add(htmlFontPanel);

        popupMenuPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(CommonUIPanel.class, "CommonUIPanel.popupMenuPanel.border.title"))); // NOI18N
        popupMenuPanel.setPreferredSize(new java.awt.Dimension(562, 46));
        popupMenuPanel.setLayout(new java.awt.BorderLayout());

        org.openide.awt.Mnemonics.setLocalizedText(iconsVisibleCB, org.openide.util.NbBundle.getMessage(CommonUIPanel.class, "CommonUIPanel.iconsVisibleCB.text")); // NOI18N
        iconsVisibleCB.setFocusPainted(false);
        popupMenuPanel.add(iconsVisibleCB, java.awt.BorderLayout.CENTER);

        variousPanel.add(popupMenuPanel);

        add(variousPanel);
    }// </editor-fold>//GEN-END:initComponents

    void load() {
        DemetraUI options = DemetraUI.getDefault();
        colorSchemeChoicePanel.setContent(ColorSchemeManager.getDefault().getColorSchemes().stream().map(ColorSchemeNamedService::new).collect(Collectors.toList()));
        colorSchemeChoicePanel.getExplorerManager().addVetoableChangeListener(this);
        colorSchemeChoicePanel.setSelectedServiceName(options.getColorSchemeName());
        dataFormatComponent.setObsFormat(options.getObsFormat());
        dataFormatComponent.addPropertyChangeListener(this);
        growthLastYears.setValue(options.getGrowthLastYears());
        iconsVisibleCB.setSelected(options.isPopupMenuIconsVisible());
        jSlider1.setValue(options.getHtmlZoomRatio());
     }

    void store() {
        DemetraUI options = DemetraUI.getDefault();
        options.setColorSchemeName(colorSchemeChoicePanel.getSelectedServiceName());
        options.setObsFormat(dataFormatComponent.getObsFormat());
        options.setGrowthLastYears((Integer) growthLastYears.getValue());
        options.setPopupMenuIconsVisible(iconsVisibleCB.isSelected());
        options.setHtmlZoomRatio(jSlider1.getValue());
    }

    boolean valid() {
        // TODO check whether form is consistent and complete
        return true;
    }

    @Override
    public void vetoableChange(PropertyChangeEvent evt) throws PropertyVetoException {
        if (ExplorerManager.PROP_SELECTED_NODES.equals(evt.getPropertyName())) {
            Node[] nodes = (Node[]) evt.getNewValue();
            if (nodes.length > 0) {
                ColorSchemeNamedService tmp = nodes[0].getLookup().lookup(ColorSchemeNamedService.class);
                colorSchemePreviewer.setColorScheme(tmp.getColorScheme());
                colorSchemePreviewer.setTitle(tmp.getDisplayName());
            }
        }
    }

    @Override
    public void propertyChange(PropertyChangeEvent evt) {
        if (evt.getPropertyName().equals(JObsFormatComponent.OBS_FORMAT_PROPERTY) && evt.getNewValue() != null) {
            colorSchemePreviewer.setObsFormat(dataFormatComponent.getObsFormat());
        }
    }

    JObsFormatComponent getDataFormatComponent() {
        return dataFormatComponent;
    }

    @lombok.AllArgsConstructor
    static final class ColorSchemeNamedService implements NamedService {

        @lombok.Getter
        private final ColorScheme colorScheme;

        @Override
        public String getName() {
            return colorScheme.getName();
        }

        @Override
        public String getDisplayName() {
            return colorScheme.getDisplayName();
        }

        @Override
        public Image getIcon(int type, boolean opened) {
            return ImageUtilities.icon2Image(HasColorSchemeSupport.iconOf(colorScheme));
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel chartPreviewPanel;
    private javax.swing.JPanel chartsPanel;
    private demetra.desktop.nodes.NamedServiceChoicePanel colorSchemeChoicePanel;
    private javax.swing.JLabel colorSchemeLabel;
    private demetra.desktop.components.JObsFormatComponent dataFormatComponent;
    private javax.swing.JLabel dataFormatLabel;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JPanel growthChartsPanel;
    private javax.swing.JSpinner growthLastYears;
    private javax.swing.JPanel htmlFontPanel;
    private javax.swing.JCheckBox iconsVisibleCB;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JLabel lastYearsLabel;
    private javax.swing.JPanel popupMenuPanel;
    private javax.swing.JPanel variousPanel;
    // End of variables declaration//GEN-END:variables
}
