/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.nbdemetra.sa.advanced;

import ec.nbdemetra.ws.WorkspaceFactory;
import ec.nbdemetra.ws.WorkspaceItem;
import ec.nbdemetra.ws.ui.WorkspaceTsTopComponent;
import ec.tss.sa.documents.GeneralizedAirlineDocument;
import ec.ui.view.tsprocessing.TsProcessingViewer;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(dtd = "-//ec.nbdemetra.sa.advanced//GeneralizedAirline//EN",
autostore = false)
@TopComponent.Description(preferredID = "GeneralizedAirlineTopComponent",
//iconBase="SET/PATH/TO/ICON/HERE", 
persistenceType = TopComponent.PERSISTENCE_NEVER)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@ActionID(category = "Seasonal Adjustment", id = "ec.nbdemetra.sa.advanced.GeneralizedAirlineTopComponent")
@ActionReference(path = "Menu/Statistical methods/Seasonal Adjustment/Single Analysis", position = 1700)
@TopComponent.OpenActionRegistration(displayName = "#CTL_GeneralizedAirlineAction")
@NbBundle.Messages({
    "CTL_GeneralizedAirlineAction=Generalized Airline",
    "CTL_GeneralizedAirlineTopComponent=Generalized Airline Window",
    "HINT_GeneralizedAirlineTopComponent=This is a Generalized Airline window"
})
public final class GeneralizedAirlineTopComponent extends WorkspaceTsTopComponent<GeneralizedAirlineDocument> {

    private static GeneralizedAirlineDocumentManager manager(){
        return WorkspaceFactory.getInstance().getManager(GeneralizedAirlineDocumentManager.class);
    }
    
    public GeneralizedAirlineTopComponent() {
        super(manager().create(WorkspaceFactory.getInstance().getActiveWorkspace()));
        initDocument();
    }

    public GeneralizedAirlineTopComponent(WorkspaceItem<GeneralizedAirlineDocument> doc) {
        super(doc);
        initDocument();
    }

    private void initDocument() {
        initComponents();
        setToolTipText(NbBundle.getMessage(GeneralizedAirlineTopComponent.class, "HINT_GeneralizedAirlineTopComponent"));
        setName(getDocument().getDisplayName());
        panel = TsProcessingViewer.create(getDocument().getElement());
        this.add(panel);
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    @Override
    protected String getContextPath() {
        return GeneralizedAirlineDocumentManager.CONTEXTPATH;
    }
}
