/*
 * Copyright 2013-2014 National Bank of Belgium
 * 
 * Licensed under the EUPL, Version 1.1 or – as soon they will be approved 
 * by the European Commission - subsequent versions of the EUPL (the "Licence");
 * You may not use this work except in compliance with the Licence.
 * You may obtain a copy of the Licence at:
 * 
 * http://ec.europa.eu/idabc/eupl
 * 
 * Unless required by applicable law or agreed to in writing, software 
 * distributed under the Licence is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the Licence for the specific language governing permissions and 
 * limitations under the Licence.
 */
package ec.nbdemetra.sa.advanced;

import ec.nbdemetra.ws.WorkspaceFactory;
import ec.nbdemetra.ws.WorkspaceItem;
import ec.nbdemetra.ws.ui.WorkspaceTopComponent;
import ec.tss.sa.documents.MixedFrequenciesArimaDocument;
import ec.ui.view.tsprocessing.Ts2ProcessingViewer;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//ec.nbdemetra.sa.advanced//MixedFrequenciesArima//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "MixedFrequenciesArimaTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_NEVER
)
//@TopComponent.Registration(mode = "output", openAtStartup = false)
//@ActionID(category = "Window", id = "ec.nbdemetra.sa.advanced.MixedFrequenciesArimaTopComponent")
//@ActionReference(path = "Menu/Statistical methods/Seasonal Adjustment/Single Analysis", position = 1700)
//@TopComponent.OpenActionRegistration(
//        displayName = "#CTL_MixedFrequenciesArimaAction"
//)
@Messages({
    "CTL_MixedFrequenciesArimaAction=Mixed Frequencies Arima",
    "CTL_MixedFrequenciesArimaTopComponent=Mixed Frequencies Arima Window",
    "HINT_MixedFrequenciesArimaTopComponent=This is a Mixed Frequencies Arima window"
})
public final class MixedFrequenciesArimaTopComponent extends WorkspaceTopComponent<MixedFrequenciesArimaDocument> {

    private static MixedFrequenciesArimaDocumentManager manager() {
        return WorkspaceFactory.getInstance().getManager(MixedFrequenciesArimaDocumentManager.class);
    }
    protected Ts2ProcessingViewer panel;

    public MixedFrequenciesArimaTopComponent() {
        super(null);
        initDocument();
    }

    public MixedFrequenciesArimaTopComponent(WorkspaceItem<MixedFrequenciesArimaDocument> doc) {
        super(doc);
        initDocument();
    }

    public void initDocument() {
        setName(getDocument().getDisplayName());
        setToolTipText(Bundle.CTL_MixedFrequenciesArimaTopComponent());
        initComponents();
        panel = Ts2ProcessingViewer.create(this.getDocument().getElement(), "High-freq sSeries", "Low-freq series");
        add(panel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        super.componentOpened();
        if (panel != null) {
            panel.doLayout();
        }
    }

    @Override
    public void componentClosed() {
        super.componentClosed();
        if (panel != null) {
            panel.dispose();
        }
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    @Override
    protected String getContextPath() {
        return MixedFrequenciesArimaDocumentManager.CONTEXTPATH; //To change body of generated methods, choose Tools | Templates.
    }
}
