/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.nbdemetra.x13;

import ec.nbdemetra.ws.WorkspaceFactory;
import ec.nbdemetra.ws.WorkspaceItem;
import ec.nbdemetra.ws.ui.WorkspaceTsTopComponent;
import ec.tss.sa.documents.X13Document;
import ec.ui.view.tsprocessing.TsProcessingViewer;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(dtd = "-//ec.nbdemetra.x13//X13//EN",
autostore = false)
@TopComponent.Description(preferredID = "X13TopComponent",
//iconBase="SET/PATH/TO/ICON/HERE", 
persistenceType = TopComponent.PERSISTENCE_NEVER)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@ActionID(category = "Seasonal Adjustment", id = "ec.nbdemetra.x13.X13TopComponent")
@ActionReference(path = "Menu/Statistical methods/Seasonal Adjustment/Single Analysis", position = 1100, separatorAfter = 1200)
@TopComponent.OpenActionRegistration(displayName = "#CTL_X13Action")
@NbBundle.Messages({
    "CTL_X13Action=X13",
    "CTL_X13TopComponent=X13 Window",
    "HINT_X13TopComponent=This is a X13 window"
})
public final class X13TopComponent extends WorkspaceTsTopComponent<X13Document> {

    private static X13DocumentManager manager() {
        return WorkspaceFactory.getInstance().getManager(X13DocumentManager.class);
    }

    public X13TopComponent() {
        super(manager().create(WorkspaceFactory.getInstance().getActiveWorkspace()));
       initDocument();
    }

    public X13TopComponent(WorkspaceItem<X13Document> doc) {
       super(doc);
        initDocument();
    }

    private void initDocument() {
        initComponents();
        setToolTipText(Bundle.HINT_X13TopComponent());
        panel = TsProcessingViewer.create(getDocument().getElement());
        this.add(panel);
        setName(getDocument().getDisplayName());
        panel.refreshHeader();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
 
    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
    
    @Override
    public String getContextPath(){
        return X13DocumentManager.CONTEXTPATH;
    }
}
