/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package demetra.desktop.x13.ui;

import demetra.desktop.ui.processing.DocumentUIServices;
import demetra.desktop.ui.processing.TsProcessingViewer;
import demetra.desktop.workspace.WorkspaceFactory;
import demetra.desktop.workspace.WorkspaceItem;
import demetra.desktop.workspace.ui.WorkspaceTsTopComponent;
import jdplus.x13.X13Document;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.explorer.ExplorerManager;
import org.openide.explorer.ExplorerUtils;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(dtd = "-//demetra.desktop.x13.ui//X13//EN",
autostore = false)
@TopComponent.Description(preferredID = "X13TopComponent",
//iconBase="SET/PATH/TO/ICON/HERE", 
persistenceType = TopComponent.PERSISTENCE_NEVER)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@ActionID(category = "Seasonal Adjustment", id = "demetra.desktop.x13.ui.X13TopComponent")
@ActionReference(path = "Menu/Statistical methods/Seasonal Adjustment/Single Analysis", position = 1000)
@TopComponent.OpenActionRegistration(displayName = "#CTL_X13Action")
@NbBundle.Messages({
    "CTL_X13Action=X13",
    "CTL_X13TopComponent=X13 Window",
    "HINT_X13TopComponent=This is a X13 window"
})
public final class X13TopComponent extends WorkspaceTsTopComponent<X13Document> {

    private final ExplorerManager mgr = new ExplorerManager();

    private static X13DocumentManager manager() {
        return WorkspaceFactory.getInstance().getManager(X13DocumentManager.class);
    }

    public X13TopComponent() {
        this(manager().create(WorkspaceFactory.getInstance().getActiveWorkspace()));
    }

    public X13TopComponent(WorkspaceItem<X13Document> doc) {
        super(doc);
        initDocument();
        associateLookup(ExplorerUtils.createLookup(mgr, getActionMap()));
    }

    @Override
    public ExplorerManager getExplorerManager() {
        return mgr;
    }

    private void initDocument() {
        initComponents();
        setToolTipText(NbBundle.getMessage(X13TopComponent.class, "HINT_X13TopComponent"));
        setName(getDocument().getDisplayName());
        panel = TsProcessingViewer.create(getDocument().getElement(), DocumentUIServices.forDocument(X13Document.class));
        this.add(panel);
        panel.refreshHeader();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    @Override
    protected String getContextPath() {
        return X13DocumentManager.CONTEXTPATH;
    }
}
