/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.nbdemetra.businesscycle;

import ec.nbdemetra.ws.WorkspaceFactory;
import ec.nbdemetra.ws.WorkspaceItem;
import ec.nbdemetra.ws.ui.WorkspaceTsTopComponent;
import ec.tss.businesscycle.documents.HodrickPrescottDocument;
import ec.ui.view.tsprocessing.TsProcessingViewer;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(dtd = "-//ec.nbdemetra.businesscycle//HodrickPrescott//EN",
autostore = false)
@TopComponent.Description(preferredID = "HodrickPrescottTopComponent",
//iconBase="SET/PATH/TO/ICON/HERE", 
persistenceType = TopComponent.PERSISTENCE_NEVER)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@ActionID(category = "Business Cycle", id = "ec.nbdemetra.businesscycle.HodrickPrescottTopComponent")
@ActionReference(path = "Menu/Statistical methods/Business Cycle" /*
 * , position = 333
 */)
@TopComponent.OpenActionRegistration(displayName = "#CTL_HodrickPrescottAction")
@NbBundle.Messages({
    "CTL_HodrickPrescottAction=Hodrick-Prescott",
    "CTL_HodrickPrescottTopComponent=HodrickPrescott Window",
    "HINT_HodrickPrescottTopComponent=This is a HodrickPrescott window"
})
public final class HodrickPrescottTopComponent extends WorkspaceTsTopComponent<HodrickPrescottDocument> {

    private static HodrickPrescottManager manager(){
        return WorkspaceFactory.getInstance().getManager(HodrickPrescottManager.class);
    }

    public HodrickPrescottTopComponent() {
        super(manager().create(WorkspaceFactory.getInstance().getActiveWorkspace()));
        initDocument();
    }

    public HodrickPrescottTopComponent(WorkspaceItem<HodrickPrescottDocument> doc) {
        super(doc);
        initDocument();
    }

    private void initDocument() {
        initComponents();
        setName(getDocument().getDisplayName());
        setToolTipText(NbBundle.getMessage(HodrickPrescottTopComponent.class, "HINT_HodrickPrescottTopComponent"));
        panel = TsProcessingViewer.create(getDocument().getElement());
        this.add(panel);

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    @Override
    protected String getContextPath() {
        return HodrickPrescottManager.CONTEXT_PATH;
    }
}
