name: Check links in documentation

on:
  push:
    paths:
      - '.github/workflows/check-links.yml'
      - 'lychee.toml'
      - '**/*.md'
  schedule:
    # Run on the first of each month at 9:00 AM
    - cron: "0 9 1 * *"
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref }}"
  cancel-in-progress: true

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Restore lychee cache
        uses: actions/cache@v3
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      - name: Check links
        id: lychee
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          fail: true
          args: --max-concurrency 1 --cache --no-progress --exclude-all-private './**/*.md'
