name: Java-EA with Maven

on:
  push:
    branches:
      - develop
  workflow_dispatch:

env:
  MAVEN_ARGS: "-B -ntp"

jobs:
  build-and-test-job:
    strategy:
      fail-fast: false
      matrix:
        java: [ 23 ]
        os:
          - ubuntu-latest     # Linux x64
          - ubuntu-24.04-arm  # Linux arm64
          - macos-latest      # macOS arm64

    name: JDK${{ matrix.java }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout and Setup Maven
        uses: s4u/setup-maven-action@v1.18.0
        with:
          checkout-submodules: true
          checkout-fetch-depth: 0
          java-version: ${{ matrix.java }}

      - name: Pre-download dependencies with Maven
        uses: nick-fields/retry@v3
        with:
          command: mvn -U dependency:go-offline
          max_attempts: 3
          timeout_minutes: 5

      - name: Build and (headless) test with Maven (Linux)
        if: ${{ runner.os == 'Linux' }}
        run: xvfb-run mvn verify

      - name: Build and (headless) test with Maven (Windows and macOS)
        if: ${{ runner.os != 'Linux' }}
        run: mvn verify
