name: "🛡️ Submit Maven Dependencies"

on:
  push:
    branches: [ "develop" ]

env:
  MAVEN_ARGS: "-B -ntp"

permissions:
  contents: write

jobs:
  submit-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: ⚙️ Checkout and Setup Maven
        uses: s4u/setup-maven-action@v1.21.0

      - name: 📤 Submit Dependency Graph
        uses: advanced-security/maven-dependency-submission-action@v6
